# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
      - netbsd
      - dragonfly
      - solaris
    goarch:
      - amd64
      - 386
      - arm64
      - arm
      - ppc64
      - ppc64le
      - mips
      - mipsle
      - mips64
      - mips64le
      - s390x
      - riscv64
    goarm:
      - 5
      - 6
      - 7
    # 忽略不支持的平台组合
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: ppc64
      - goos: darwin
        goarch: ppc64le
      - goos: darwin
        goarch: mips
      - goos: darwin
        goarch: mipsle
      - goos: darwin
        goarch: mips64
      - goos: darwin
        goarch: mips64le
      - goos: darwin
        goarch: s390x
      - goos: darwin
        goarch: riscv64
      - goos: windows
        goarch: arm
        goarm: 5
      - goos: windows
        goarch: ppc64
      - goos: windows
        goarch: ppc64le
      - goos: windows
        goarch: mips
      - goos: windows
        goarch: mipsle
      - goos: windows
        goarch: mips64
      - goos: windows
        goarch: mips64le
      - goos: windows
        goarch: s390x
      - goos: windows
        goarch: riscv64
      - goos: solaris
        goarch: 386
      - goos: solaris
        goarch: arm
      - goos: solaris
        goarch: arm64
      - goos: solaris
        goarch: ppc64
      - goos: solaris
        goarch: ppc64le
      - goos: solaris
        goarch: mips
      - goos: solaris
        goarch: mipsle
      - goos: solaris
        goarch: mips64
      - goos: solaris
        goarch: mips64le
      - goos: solaris
        goarch: riscv64
    ldflags:
      - -s -w
      - -X github.com/cyberspacesec/go-snir/pkg/ascii.version={{.Version}}
      - -X github.com/cyberspacesec/go-snir/pkg/ascii.commit={{.Commit}}
      - -X github.com/cyberspacesec/go-snir/pkg/ascii.buildDate={{.Date}}
      - -X github.com/cyberspacesec/go-snir/pkg/ascii.buildTime={{.Env.BUILD_TIME}}
    binary: snir
    main: .
    id: "snir"
    
archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*
      - docs/*

checksum:
  name_template: 'checksums.txt'
  
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch
      
brews:
  - name: snir
    repository:
      owner: cyberspacesec
      name: homebrew-tap
    homepage: "https://github.com/cyberspacesec/go-snir"
    description: "一个强大的网页截图和信息收集工具"
    license: "MIT"
    install: |
      bin.install "snir"
    test: |
      system "#{bin}/snir version" 